import Balance from "@/components/balance/balance";
import Chart from "@/components/chart/chart";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Expenses chart component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main>
        <Balance />
        <Chart />
        <div className="attribution">
          Challenge by &nbsp;
          <a
            href="https://www.frontendmentor.io/challenges/results-summary-component-CE_K6s0maV"
            target="_blank"
          >
            Frontend Mentor.
          </a>
          &nbsp; Coded by &nbsp;
          <a href="https://github.com/michellepennat">Michelle Penna</a>.
        </div>
      </main>
    </>
  );
}
